name: Typo / Grammar fix
description: If you've found a typo or grammar issue, use this.
labels: ["bug", "docs"]
assignees:
  - nostromos
body:
  - type: markdown
    attributes:
      value: |
        ## PR Welcome!

        If the typo / grammar issue is trivial and straightforward, you can help by skipping this form and submitting a PR directly.
        If you spot multiple, please combine them into a single PR. Thanks!

        If you're too lazy to do that, just submit this.
  - type: textarea
    id: description
    attributes:
      label: Description
